server {
    listen 80;
    server_name www.socket-serverv1.ms-associes-digital.com;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name www.socket-serverv1.ms-associes-digital.com;

    ssl_certificate     /etc/letsencrypt/live/www.socket-serverv1.ms-associes-digital.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.socket-serverv1.ms-associes-digital.com/privkey.pem; #sudo certbot --nginx -d www.soscket-serverv1.ms-associes-digital.com


    location / {
        proxy_pass http://localhost:3037;   # your Node.js Socket.IO server port

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Preserve client info
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Long-lived connections
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }
}
